'\" t
.\"     Title: arch-install
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 02/03/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ARCH\-INSTALL" "3" "02/03/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
arch-install \- Install an Arch Linux system from the bootable media\&.
.SH "VARIABLES"
.PP
\fI$MNT\fR
.RS 4
The mountpoint where to install the system\&. Defaults to
\fI/mnt\fR\&.
.RE
.SH "FUNCTIONS"
.PP
\fBchrootx\fR
.RS 4
Executes a command in chroot\&.
.PP
\fI$@\fR
.RS 4
Arguments for
\fBarch\-chroot\fR\&.
.RE
.RE
.PP
\fBmirrorlist\fR
.RS 4
Retrieves a mirrorlist in
\fI/etc/pacman\&.d/mirrorlist\fR
for given country code\&.
.PP
\fI$1\fR
.RS 4
Country code (\(oqUS\(cq, \(oqGB\(cq, \(oqFR\(cq, etc)\&.
.RE
.RE
.PP
\fBbootstrap\fR
.RS 4
Bootstraps the system in mountpoint\&.
.PP
\fI$@\fR
.RS 4
Packages to install with for
\fBpacstrap\fR\&.
.RE
.RE
.PP
\fBfstab\fR
.RS 4
Generates the fstab in mountpoint\&.
.PP
\fI$@\fR
.RS 4
Arguments for
\fBgenfstab\fR\&.
.RE
.RE
.PP
\fBlocale\fR
.RS 4
Generates given locale in mountpoint\&.
.PP
\fI$1\fR
.RS 4
Locale (\(oqen_US\(cq, \(oqen_US\&.UTF\-8\(cq, etc)\&.
.RE
.RE
.PP
\fBlinux\fR
.RS 4
Creates initial RAM disk for Linux\&.
.RE
.PP
\fBsyslinuxi\fR
.RS 4
Installs Syslinux in mointpoint\&.
.PP
\fI$1\fR
.RS 4
Disk to install the bootloader on (\(oqsda1\(cq, \(oqsda2\(cq, etc)\&.
.RE
.RE
.PP
\fBautoconfigure\fR
.RS 4
Adds the configure script in
\fI/root/\&.profile\fR
to autorun it at next login\&.
.RE
.PP
\fBfinish\fR
.RS 4
Prompts for root password, unmount mountpoint recursively and reboots\&.
.RE
.SH "SEE ALSO"
.sp
\fBarch\-configure\fR(1), \fBarch\-chroot\fR, https://www\&.archlinux\&.org/mirrorlist/, \fBpacstrap\fR, \fBgenfstab\fR, \fBlocale\-gen\fR, \fBmkinitcpio\fR(8), \fBsyslinux\fR(1), \fBsyslinux\-install_update\fR\&.
