#!/usr/bin/env sh

set -e

. "$(dirname "$0")/../arch-install.sh"

#PART=/dev/sda5
LABEL=arch

share() {
    mkdir "$MNT/share"
    #mount /dev/sda6 "$MNT/share"
    #mount.ntfs /dev/sda6 "$MNT/share"
}

# Disk setup
fdisk /dev/sda
mkfs.ext4 "$PART"
e2label "$PART" "$LABEL"
mount "$PART" "$MNT"
#share

# Mirrorlist
mirrorlist FR

# Install base system
bootstrap base base-devel

# NTFS support
#bootstrap ntfs-3g

# Make fstab with labels
fstab -L

# Locale
locale en_US.UTF-8

# RAM disk
linux

# Install bootloader
syslinuxi "$PART"

# Copy program directory
cp -R "$(dirname "$0")/.." "$MNT/root/arch-deploy"

# Autorun configure after reboot
autoconfigure "arch-deploy/examples/configure"

# Finish install
finish
